package Swing;
import javax.swing.*;

import javax.swing.JFrame;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author basak
 */
public class FarmAppSwing extends javax.swing.JFrame {
    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form FarmAppSwing
     */
    public FarmAppSwing() {
        initComponents();

        lstMenuOptions.setModel(model);
        model.addElement("1. ADD COW");
        model.addElement("2. DELETE COW");
        model.addElement("3. GET COW DETAILS");
        model.addElement("4. ADD VET");
        model.addElement("5. DELETE VET");
        model.addElement("6. GET VET DETAILS");
        model.addElement("7. ADD TREATMENTS");
        model.addElement("8. GET COW TREATMENTS");
        model.addElement("9. GET COW TREATMENTS WITH DATE");
        model.addElement("10. LIST COWS");
        model.addElement("11. LIST VETS");
        model.addElement("12. FEED THE ANIMALS");
        model.addElement("13. GET EMPLOYEE SALARY");
        model.addElement("14. ADD MILKING MEASUREMENTS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstMenuOptions = new javax.swing.JList<>();
        lblOption = new javax.swing.JLabel();
        btnOptions = new javax.swing.JButton();
        txtOptions = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNewProject = new javax.swing.JMenuItem();
        jMenuItemNewFile = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemundo = new javax.swing.JMenuItem();
        jMenuItemredo = new javax.swing.JMenuItem();
        jMenuItemcopy = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO THE FARM APP !");

        jScrollPane1.setViewportView(lstMenuOptions);

        lblOption.setText("Option:");

        btnOptions.setText("select");
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });

        txtOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOptionsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItemNewProject.setText("new project");
        jMenu1.add(jMenuItemNewProject);

        jMenuItemNewFile.setText("new file");
        jMenu1.add(jMenuItemNewFile);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemundo.setText("undo");
        jMenuItemundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemundoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemundo);

        jMenuItemredo.setText("redo");
        jMenuItemredo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemredoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemredo);

        jMenuItemcopy.setText("cut");
        jMenuItemcopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcopyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemcopy);

        jMenuItem4.setText("copy");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblOption, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(txtOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(btnOptions)))
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblOption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(btnOptions)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(129, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemundoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemcopyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItemredoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtOptionsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {
        String option = txtOptions.getText();

        if(option.equals("1")){
            addCowSwing addCowSwing = new addCowSwing();
            this.setVisible(false);
            addCowSwing.setVisible(true);
        }
        else if(option.equals("2")){
            deleteCowSwing deleteCowSwing = new deleteCowSwing();
            this.setVisible(false);
            deleteCowSwing.setVisible(true);
        }
        else if(option.equals("3")){
            getCowDetailsSwing getCowDetailsSwing = new getCowDetailsSwing();
            this.setVisible(false);
            getCowDetailsSwing.setVisible(true);
        }
        else if(option.equals("4")){
            addVetSwing addVetSwing = new  addVetSwing();
            this.setVisible(false);
            addVetSwing.setVisible(true);
        }
        else if(option.equals("5")){
            deleteVetSwing deleteVetSwing = new deleteVetSwing();
            this.setVisible(false);
            deleteVetSwing.setVisible(true);
        }
        else if(option.equals("6")){
            getVetDetailsSwing getVetDetailsSwing = new getVetDetailsSwing();
            this.setVisible(false);
            getVetDetailsSwing.setVisible(true);
        }
        else if(option.equals("7")){
            addTreatmentSwing addTreatmentSwing = new addTreatmentSwing();
            this.setVisible(false);
            addTreatmentSwing.setVisible(true);
        }
        else if(option.equals("8")){
            getTreatmentsSwing getTreatmentsSwing = new getTreatmentsSwing();
            this.setVisible(false);
            getTreatmentsSwing.setVisible(true);
        }
        else if(option.equals("9")){
            getTreatmentsSwing getTreatmentsSwing = new getTreatmentsSwing();
            this.setVisible(false);
            getTreatmentsSwing.setVisible(true);
        }
        else if(option.equals("10")){
            listCowSwing listCowSwing = new listCowSwing();
            this.setVisible(false);
            listCowSwing.setVisible(true);
        }
        else if(option.equals("11")){
            listVetSwing listVetSwing = new listVetSwing();
            this.setVisible(false);
            listVetSwing.setVisible(true);
        }
        else if(option.equals("12")){
            /*feedTheAnimalSwing feedTheAnimalSwing = new feedTheAnimalSwing();
            this.setVisible(false);
            feedTheAnimalSwingsetVisible(true);*/
        }
        else if(option.equals("13")){
            getEmployeeSalarySwing getEmployeeSalarySwing = new getEmployeeSalarySwing();
            this.setVisible(false);
            getEmployeeSalarySwing.setVisible(true);
        }
        else if(option.equals("14")){
           /* AddMilkingSwing addMilkingSwing = new AddMilkingSwing();
            this.setVisible(false);
            addMilkingSwing.setVisible(true);*/
        }
        else{}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmAppSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnOptions;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemNewFile;
    private javax.swing.JMenuItem jMenuItemNewProject;
    private javax.swing.JMenuItem jMenuItemcopy;
    private javax.swing.JMenuItem jMenuItemredo;
    private javax.swing.JMenuItem jMenuItemundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOption;
    private javax.swing.JList<String> lstMenuOptions;
    private javax.swing.JTextField txtOptions;
    // End of variables declaration
}
